sudo: required

dist: trusty

services:
    - docker

language: node_js

node_js:
  - "9"

os:
    - linux

env:
    global:
        - IMAGE_NAME= < < github profile > > /%project-name%
        - DOCKERFILE_LOCATION="$IMAGE_NAME"
        - IMAGE_TAG="$TRAVIS_BUILD_NUMBER"

before_deploy:
  # create a docker image tag for develop branch
  - if [[ $TRAVIS_BRANCH == "develop" ]]; then export IMAGE_TAG=$TRAVIS_BUILD_NUMBER-dev; fi
  # create a docker image tag for release branch
  - if [[ $TRAVIS_BRANCH == "release" ]]; then export IMAGE_TAG=$TRAVIS_BUILD_NUMBER-rc; fi
  # create a docker image tag for git tags
  - if [[ $TRAVIS_TAG ]]; then export IMAGE_TAG=$TRAVIS_TAG; fi
  - echo "$IMAGE_TAG"
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  # create docker image for develop branch
  - provider: script
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      branch: develop
  # create docker image for release branch
  - provider: script
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      branch: release
  # create docker image for tags
  - provider: script
    script: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
    on:
      tags: true


notifications:
  email:
    on_success: never
    on_failure: always
