version: '2'
services:
  app:
    build:
       context: .
       dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    environment:
      NODE_ENV: production
      PORT: 3000
      STATIC_SUB_DIR: '/app/dist/static'